name: ci

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup
        uses: ./.github/actions/setup

      - name: check
        run: pnpm run check:ci

      - name: check cloudflare pages build
        run: pnpm run build

      - name: clean build artifacts
        run: pnpm run clean

      - name: check github pages build
        env:
          PUBLIC_BASE: /${{ github.event.repository.name }}
          PUBLIC_SITE: https://${{ github.repository_owner }}.github.io
        run: pnpm run build
